language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install

script: phpunit --coverage-text --configuration tests/phpunit.xml
