language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 7

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  - composer install


script: phpunit --coverage-text --configuration tests/phpunit.xml
